import { FC } from 'react';
import Head from 'next/head';

interface CustomHeadProps {
    title: string;
}
const CustomHead: FC<CustomHeadProps> = ({ title = 'Payment Gateway' }) => {
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
};

export default CustomHead;
